import type { Metadata } from "next";
import "./globals.css";
import Nav from "./(Components)/nav";

export const metadata: Metadata = {
  title: "Next Auth App",
  description: "Generated by Muhyadin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-gray-100">
        <Nav />
        <div className=" m-2">{children}</div>
      </body>
    </html>
  );
}
